// ABOUTME: Exports WebsiteConfig to standalone HTML file
// ABOUTME: Generates static HTML with Tailwind CSS via CDN

import { WebsiteConfig } from '../types/website-config';

/**
 * Export a WebsiteConfig to a standalone HTML file
 * Uses Tailwind CSS CDN for styling
 */
export function exportToHTML(config: WebsiteConfig): string {
  const { theme, metadata, blocks } = config;

  // Generate CSS custom properties for theme
  const themeCSS = `
    :root {
      --color-primary: ${theme.colors.primary};
      --color-secondary: ${theme.colors.secondary};
      --color-background: ${theme.colors.background};
      --color-text: ${theme.colors.text};
      --color-muted: ${theme.colors.muted};
      --font-heading: ${theme.fonts.heading};
      --font-body: ${theme.fonts.body};
    }

    body {
      font-family: var(--font-body), system-ui, -apple-system, sans-serif;
      color: var(--color-text);
      background-color: var(--color-background);
    }

    h1, h2, h3, h4, h5, h6 {
      font-family: var(--font-heading), system-ui, -apple-system, sans-serif;
    }
  `;

  // Generate HTML for blocks (simplified - just show a message)
  const blocksHTML = `
    <main class="min-h-screen">
      <div class="container mx-auto px-4 py-16 text-center">
        <h1 class="text-4xl font-bold mb-4">Website Export</h1>
        <p class="text-lg text-gray-600 mb-8">This is a static export of your website.</p>
        <p class="text-sm text-gray-500">
          Your website contains ${blocks.length} block${blocks.length !== 1 ? 's' : ''}.
        </p>
        <p class="text-sm text-gray-500 mt-4">
          For a fully functional website, please deploy through the editor.
        </p>
      </div>
    </main>
  `;

  // Complete HTML document
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${escapeHTML(metadata.description)}">
  ${metadata.author ? `<meta name="author" content="${escapeHTML(metadata.author)}">` : ''}
  <title>${escapeHTML(metadata.title)}</title>

  <!-- Tailwind CSS CDN -->
  <script src="https://cdn.tailwindcss.com"></script>

  <!-- Custom Theme -->
  <style>
    ${themeCSS}
  </style>
</head>
<body>
  ${blocksHTML}

  <!-- Generated by Prompt to Website -->
  <footer class="border-t py-8 mt-16">
    <div class="container mx-auto px-4 text-center text-sm text-gray-500">
      <p>Generated with Prompt to Website</p>
    </div>
  </footer>
</body>
</html>`;

  return html;
}

/**
 * Escape HTML special characters to prevent XSS
 */
function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Download HTML as a file in the browser
 */
export function downloadHTML(html: string, filename: string = 'website.html'): void {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
